steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run/doc-app-research-uploads:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run/doc-app-research-uploads:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy doc-app-research-uploads \
          --image "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run/doc-app-research-uploads:latest" \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "GCP_PROJECT_ID=$PROJECT_ID,GCP_LOCATION=us-central1,STORAGE_BUCKET=$PROJECT_ID-doc-assets-resup,APP_ENV=researchuploads,APP_VERSION=research-uploads-$SHORT_SHA" \
          --memory 2Gi \
          --timeout 3600 \
          --cpu 2

options:
  logging: CLOUD_LOGGING_ONLY
